#ifndef __ODBCONFIG_H__
#define __ODBCONFIG_H__

#define CAN_SPI_CS_PIN 9


#define REALDATA_TIMEFRAME 500
#define SIMULATION_TIMEFRAME 2000

#define MAX_SPEED 200
#define MIN_SPEED 0
#define MAX_RPM 9000
#define MIN_RPM 0
#define MAX_TEMP 100
#define MIN_TEMP 0
#define MAX_FUELLEVEL 100
#define MIN_FUELLEVEL 0

#define GAUGE_MAX_SPEED_DEGREE 135
#define GAUGE_MIN_SPEED_DEGREE 225


#define GAUGE_MAX_RPM_DEGREE 50
#define GAUGE_MIN_RPM_DEGREE 310


#define SIMULATION_RPM_STEP 500
#define SIMULATION_FUELLEVEL_STEP 3
#define SIMULATION_SPEED_STEP 5
#define SIMULATION_TEMP_STEP 1

#define SKETCH_VERSION "v0.2"

#endif
